import type { MenuCategory, Product } from './types'

export const defaultCategories: MenuCategory[] = [
  { id: 1, label: 'Paket', emoji: '🍱', sortOrder: 10, active: true },
  { id: 2, label: 'Ayam', emoji: '🍗', sortOrder: 20, active: true },
  { id: 3, label: 'Burger', emoji: '🍔', sortOrder: 30, active: true },
  { id: 4, label: 'Snack', emoji: '🍟', sortOrder: 40, active: true },
  { id: 5, label: 'Minuman', emoji: '🥤', sortOrder: 50, active: true },
]

export const products: Product[] = [
  {
    id: 1,
    name: 'Paket Andalan',
    description: '2 ayam krispi, nasi hangat, dan es teh manis.',
    price: 43900,
    originalPrice: 51900,
    category: 'Paket',
    emoji: '🍗',
    tone: 'gold',
    badge: 'Paling laris',
    addons: [],
  },
  {
    id: 2,
    name: 'Ayam Krispi Original',
    description: 'Menu favorit dengan rasa khas dan tekstur renyah.',
    price: 18900,
    category: 'Ayam',
    emoji: '🍗',
    tone: 'cream',
    badge: 'Favorit',
    addons: [],
  },
  {
    id: 3,
    name: 'Ayam Hot Lava',
    description: 'Ayam krispi dengan saus pedas manis yang nagih.',
    price: 23900,
    category: 'Ayam',
    emoji: '🌶️',
    tone: 'red',
    badge: 'Baru',
    spicy: true,
    addons: [],
  },
  {
    id: 4,
    name: 'Crispy Cheese Burger',
    description: 'Ayam krispi, keju, sayuran, dan saus creamy.',
    price: 28900,
    category: 'Burger',
    emoji: '🍔',
    tone: 'orange',
    addons: [],
  },
  {
    id: 5,
    name: 'Double Crunch Burger',
    description: 'Dua lapis ayam krispi untuk lapar yang serius.',
    price: 36900,
    category: 'Burger',
    emoji: '🍔',
    tone: 'yellow',
    badge: 'Extra puas',
    addons: [],
  },
  {
    id: 6,
    name: 'Kentang Bumbu',
    description: 'Kentang renyah dengan pilihan bumbu gurih.',
    price: 15900,
    category: 'Snack',
    emoji: '🍟',
    tone: 'pink',
    addons: [],
  },
  {
    id: 7,
    name: 'Crispy Chicken Bites',
    description: 'Potongan ayam tanpa tulang, pas buat sharing.',
    price: 24900,
    category: 'Snack',
    emoji: '🍿',
    tone: 'peach',
    addons: [],
  },
  {
    id: 8,
    name: 'Cola Dingin',
    description: 'Minuman bersoda dingin dan menyegarkan.',
    price: 9900,
    category: 'Minuman',
    emoji: '🥤',
    tone: 'blue',
    addons: [],
  },
]

export const formatRupiah = (value: number) =>
  new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    maximumFractionDigits: 0,
  }).format(value)
